### ISSUE TITLE
Docs issue? Where do path parameters go?

### ISSUE THREAD

**Issue by howardjones** [klen/http-router#3]
In the README, you have these two examples...

    @router.route('/users/{username}')
    def users():
        return 'result from the fn'

    @router.route('/orders/{order_id:int}')
    def orders():
        return 'result from the fn'

But where do those named parameters go? Are there supposed to be arguments on these functions, like a flask view would have?

**Comment by askfiy** [comment]
match = router("url", method)

params = match.params

**Comment by klen** [comment]
@askfiy thank you!
