### ISSUE TITLE
Docs: Response of POST?

### ISSUE THREAD

**Issue by kudomarkos** [klen/http-router#4]
Excuse me, I would like to know how to get the data received in POSTs routes.
```
@router.route('/only-post', methods=['POST'])
def only_post():
   ### Here i want to do stuff with the sent input_json which someone/something posts me.. <--------------
    return 'only-post'
```
If you code an example to doc i would apreciate
THanks in advance

**Comment by askfiy** [comment]
It only provides the function of routing and matching route parameters, and does not provide the function of parsing the request body.

**Comment by klen** [comment]
The library is not a HTTP framework. It's an utilite to build the frameworks.
The main goal of the library to bind targets to http routes and match them.
